[package]
name = "caxlang"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = { level="allow" }

[dependencies]
caxlang_proc = { version = "0.1.0", path = "../caxlang_proc" }
logos = "0.15.0"
